# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    avoid_print: false
    avoid_relative_lib_imports: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
