name: gorlaeus_bookings
description: An app for booking lecture rooms in the Gorlaeus building of Leiden University.
publish_to: 'none'

version: 1.3.0+7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc_test: ^9.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^0.13.5
  intl: ^0.17.0
  mocktail: ^0.3.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datagrid: ^20.2.44
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
